export const StateArray = [
  { key: 'Andaman and Nicobar', value: 'Andaman and Nicobar' },
  {
    key: 'Andhra Pradesh',
    value: 'Andhra Pradesh',
  },
  { key: 'Arunachal Pradesh', value: 'Arunachal Pradesh' },
  { key: 'Assam', value: 'Assam' },
  { key: 'Bihar', value: 'Bihar' },
  { key: 'Chandigarh', value: 'Chandigarh' },
  { key: 'Chhattisgarh', value: 'Chhattisgarh' },
  { key: 'Dadra and Nagar Haveli', value: 'Dadra and Nagar Haveli' },
  { key: 'Daman and Diu', value: 'Daman and Diu' },
  { key: 'Delhi', value: 'Delhi' },
  { key: 'Goa', value: 'Goa' },
  { key: 'Gujarat', value: 'Gujarat' },
  { key: 'Haryana', value: 'Haryana' },
  { key: 'Himachal Pradesh', value: 'Himachal Pradesh' },
  { key: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
  { key: 'Jharkhand', value: 'Jharkhand' },
  { key: 'Karnataka', value: 'Karnataka' },
  { key: 'Kerala', value: 'Kerala' },
  { key: 'Lakshadweep', value: 'Lakshadweep' },
  { key: 'Madhya Pradesh', value: 'Madhya Pradesh' },
  { key: 'Maharashtra', value: 'Maharashtra' },
  { key: 'Manipur', value: 'Manipur' },
  { key: 'Meghalaya', value: 'Meghalaya' },
  { key: 'Mizoram', value: 'Mizoram' },
  { key: 'Nagaland', value: 'Nagaland' },
  { key: 'Odisha', value: 'Odisha' },
  { key: 'Puducherry', value: 'Puducherry' },
  { key: 'Punjab', value: 'Punjab' },
  { key: 'Rajasthan', value: 'Rajasthan' },
  { key: 'Sikkim', value: 'Sikkim' },
  { key: 'Tamil Nadu', value: 'Tamil Nadu' },
  { key: 'Tripura', value: 'Tripura' },
  { key: 'Uttar Pradesh', value: 'Uttar Pradesh' },
  { key: 'Uttarakhand', value: 'Uttarakhand' },
  { key: 'West Bengal', value: 'West Bengal' },
];
